/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CampaignCodeRouteImport } from './routes/$campaignCode'
import { Route as IndexRouteImport } from './routes/index'

const CampaignCodeRoute = CampaignCodeRouteImport.update({
  id: '/$campaignCode',
  path: '/$campaignCode',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$campaignCode': typeof CampaignCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$campaignCode': typeof CampaignCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$campaignCode': typeof CampaignCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$campaignCode'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$campaignCode'
  id: '__root__' | '/' | '/$campaignCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignCodeRoute: typeof CampaignCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$campaignCode': {
      id: '/$campaignCode'
      path: '/$campaignCode'
      fullPath: '/$campaignCode'
      preLoaderRoute: typeof CampaignCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignCodeRoute: CampaignCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
